### PR TITLE
Update Gradle plugin and Robolectric tests

### PR DESCRIPTION
**Pull request by Vandalko**
- Update Gradle plugin and Robolectric tests
  - Reflection-based tests didn't survive
  - `ImageRequestTest.shouldCacheImages()` does not pass for some strange reason
 - Remove strict ui-net dependency
 - Enable Docker-Travis integration http://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by roman-mazur** [comment]
Please update build tools installed by travis
https://github.com/stanfy/enroscar/blob/master/.travis.yml#L5

**Comment by Vandalko** [comment]
connected tests on Android 5.0+ are behaving strange... while working on real device, they refuse to work on emulator...

**Comment by Vandalko** [comment]
they've tried to add android-22 support, but had to roll-back http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/ :(

**Comment by Vandalko** [comment]
@roman-mazur PTAL

**Pull request merged**
